services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./database:/app/database
    networks:
      - public_net



  orchestrator:
    build: ./orchestrator
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database

    networks:
      - public_net
      - internal_net

  agent_echo:
    build: ./agents/agent_echo
    networks:
      - internal_net


  agent_calendar:
    build: ./agents/agent_calendar
    env_file: .env
    volumes:
      - ./database:/app/database
    networks:
      - internal_net
      - public_net

  agent_file:
    build: ./agents/agent_file
    volumes:
      - ./shared_files:/app/shared_files:ro
    networks:
      - internal_net

  agent_telegram:
    build: ./agents/agent_telegram
    env_file: .env
    volumes:
      - ./database:/app/database
    networks:
      - internal_net
      - public_net



networks:
  public_net:
  internal_net:
    internal: true